### PR TITLE
Passing class to TimeRange, not just TimeRangeHeader

### LINKED ISSUE #71: timeRange classes not working
Nice work on the chart!
But I dont seem to be able to add classes to the timeRanges
It works for the tasks

```
timeRanges: [
      {
        id: 1,
        from: Date.parse("2022-05-16T12:25"),
        to: Date.parse("2022-05-16T12:50"),
        classes: "green",
        label: "test",
      },
      {
        id: 2,
        from: Date.parse("2022-05-16T14:25"),
        to: Date.parse("2022-05-16T14:50"),
        classes: ["currentTime"],
        label: "test2",
      },
    ]
```
image
image

version "4.0.3-beta"

### PR DESCRIPTION
**Pull request by V-Py**
fix #71

### CODE REVIEW

File: src/entities/TimeRange.svelte [hunk 1]
```diff
@@ -11,9 +11,14 @@
...
     };
+
+    function setClass(node){
+        if(!model.classes) return;
+        node.classList.add(model.classes);
+    }
 </script>
 
-<div class="sg-time-range" class:moving="{resizing}" style="width:{_position.width}px;left:{_position.x}px">
+<div class="sg-time-range" class:moving="{resizing}" style="width:{_position.width}px;left:{_position.x}px" use:setClass>
```
Comment (ANovokmet) [inline src/entities/TimeRange.svelte:21]: I know this is already merged but maybe it would be better to use class="sg-time-range {model.classes ? model.classes.join(' ') : ''}" because the value would then be bound

Comment (V-Py) [reply src/entities/TimeRange.svelte:21]: you're absolutely right, I'll do the modification tomorrow!
